substitutions:
  name: "auto-space-lite-c3c8c8"
  friendly_name: Auto Space Lite c3c8c8

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: esphome.web
    version: '1.0'

esp32:
  board: esp32-s3-devkitc-1
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:

# Allow Over-The-Air updates
ota:

# Allow provisioning Wi-Fi via serial
improv_serial:

wifi:
  # Set up a wifi access point
  ap: {}

# In combination with the `ap` this allows the user
# to provision wifi credentials to the device via WiFi AP.
captive_portal:

dashboard_import:
  package_import_url: github://esphome/firmware/esphome-web/esp32s3.yaml@v2
  import_full_config: true

# Sets up Bluetooth LE (Only on ESP32) to allow the user
# to provision wifi credentials to the device.
esp32_improv:
  authorizer: none

# To have a "next url" for improv serial
web_server:

uart:
  id: uart_mmwave
  tx_pin: 17
  rx_pin: 18
  baud_rate: 256000
  parity: NONE
  stop_bits: 1  

ld2410:

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
      internal: true
    has_moving_target:
      name: Moving Target
      internal: true
    has_still_target:
      name: Still Target
      internal: true

  - platform: gpio
    pin: 16
    id: gpio_out_pin_presence
    name: mmWave pin presence
    device_class: presence
    on_state:
      then:
        - if:
            condition:
              lambda: 'return !id(manual_mode).state;'
            then:
              - if:
                  condition:
                    lambda: 'return id(gpio_out_pin_presence).state;'
                  then:
                    - switch.turn_on: relay_1    
                  else:
                    - switch.turn_off: relay_1   

sensor:
  - platform: ld2410
    light:
      name: light
    moving_distance:
      name : Moving Distance
      internal: true
    still_distance:
      name: Still Distance
      internal: true
    moving_energy:
      name: Move Energy
      internal: true
    still_energy:
      name: Still Energy
      internal: true
    detection_distance:
      name: Detection Distance
      internal: true
    g0:
      still_energy:
        name: g0 still energy
        internal: true
    g1:
      still_energy:
        name: g1 still energy
        internal: true
    g2:
      still_energy:
        name: g2 still energy
        internal: true
    g3:
      still_energy:
        name: g3 still energy
        internal: true
    g4:
      still_energy:
        name: g4 still energy
        internal: true
    g5:
      still_energy:
        name: g5 still energy
        internal: true
    g6:
      still_energy:
        name: g6 still energy
        internal: true
    g7:
      still_energy:
        name: g7 still energy
        internal: true
    g8:
      still_energy:
        name: g8 still energy
        internal: true

switch:
  - platform: ld2410
    engineering_mode:
      name: "engineering mode"
    bluetooth:
      name: "control bluetooth"
      internal: true

  - platform: gpio  #light
    id: relay_1
    pin: 37
    name: "Relay_1"  

  - platform: template
    name: "Manual_Mode"
    id: manual_mode
    icon: mdi:link-variant
    optimistic: true
    entity_category: config
    on_turn_on:
      then:
      - switch.turn_on: manual_mode
    on_turn_off:
      then:
      - switch.turn_off: manual_mode        

number:
  - platform: ld2410
    timeout:
      name: timeout
    light_threshold:
      name: light threshold
    max_move_distance_gate:
      name: max move distance gate
    max_still_distance_gate:
      name: max still distance gate
    g0:
      move_threshold:
        name: g0 move threshold
        id: g0_move_threshold
        internal: true
      still_threshold:
        name: g0 still threshold
        id: g0_still_threshold
        internal: true
    g1:
      move_threshold:
        name: g1 move threshold
        id: g1_move_threshold
        internal: true
      still_threshold:
        name: g1 still threshold
        id: g1_still_threshold
        internal: true
    g2:
      move_threshold:
        name: g2 move threshold
        id: g2_move_threshold
        internal: true
      still_threshold:
        name: g2 still threshold
        id: g2_still_threshold
        internal: true
    g3:
      move_threshold:
        name: g3 move threshold
        id: g3_move_threshold
        internal: true
      still_threshold:
        name: g3 still threshold
        id: g3_still_threshold
        internal: true
    g4:
      move_threshold:
        name: g4 move threshold
        id: g4_move_threshold
        internal: true
      still_threshold:
        name: g4 still threshold
        id: g4_still_threshold
        internal: true
    g5:
      move_threshold:
        name: g5 move threshold
        id: g5_move_threshold
        internal: true
      still_threshold:
        name: g5 still threshold
        id: g5_still_threshold
        internal: true
    g6:
      move_threshold:
        name: g6 move threshold
        id: g6_move_threshold
        internal: true
      still_threshold:
        name: g6 still threshold
        id: g6_still_threshold
        internal: true
    g7:
      move_threshold:
        name: g7 move threshold
        id: g7_move_threshold
        internal: true
      still_threshold:
        name: g7 still threshold
        id: g7_still_threshold
        internal: true
    g8:
      move_threshold:
        name: g8 move threshold
        id: g8_move_threshold
        internal: true
      still_threshold:
        name: g8 still threshold
        id: g8_still_threshold  
        internal: true  

button:
  - platform: ld2410
    factory_reset:
      name: "factory reset"
      internal: true
    restart:
      name: "restart"
    query_params:
      name: query params
      internal: true
       
  - platform: template
    name: "Move Presets 1"
    id: move_presets_1   
    icon: "mdi:signal-cellular-1"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_move_threshold
            value: 60 
        - number.set:
            id: g1_move_threshold
            value: 60 
        - number.set:
            id: g2_move_threshold
            value: 48 
        - number.set:
            id: g3_move_threshold
            value: 36 
        - number.set:
            id: g4_move_threshold
            value: 24 
        - number.set:
            id: g5_move_threshold
            value: 18 
        - number.set:
            id: g6_move_threshold
            value: 18 
        - number.set:
            id: g7_move_threshold
            value: 18 
        - number.set:
            id: g8_move_threshold
            value: 18                                                                                     

  - platform: template
    name: "Move Presets 2"
    id: move_presets_2   
    icon: "mdi:signal-cellular-2"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_move_threshold
            value: 50 
        - number.set:
            id: g1_move_threshold
            value: 50 
        - number.set:
            id: g2_move_threshold
            value: 40 
        - number.set:
            id: g3_move_threshold
            value: 30 
        - number.set:
            id: g4_move_threshold
            value: 20 
        - number.set:
            id: g5_move_threshold
            value: 15 
        - number.set:
            id: g6_move_threshold
            value: 15 
        - number.set:
            id: g7_move_threshold
            value: 15 
        - number.set:
            id: g8_move_threshold
            value: 15 

  - platform: template
    name: "Move Presets 3"
    id: move_presets_3   
    icon: "mdi:signal-cellular-3"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_move_threshold
            value: 45 
        - number.set:
            id: g1_move_threshold
            value: 45 
        - number.set:
            id: g2_move_threshold
            value: 36 
        - number.set:
            id: g3_move_threshold
            value: 27 
        - number.set:
            id: g4_move_threshold
            value: 18 
        - number.set:
            id: g5_move_threshold
            value: 13 
        - number.set:
            id: g6_move_threshold
            value: 13 
        - number.set:
            id: g7_move_threshold
            value: 13 
        - number.set:
            id: g8_move_threshold
            value: 13 

  - platform: template
    name: "Still Presets 1"
    id: still_presets_1   
    icon: "mdi:signal-cellular-1"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_still_threshold
            value: 0 
        - number.set:
            id: g1_still_threshold
            value: 0 
        - number.set:
            id: g2_still_threshold
            value: 48 
        - number.set:
            id: g3_still_threshold
            value: 48 
        - number.set:
            id: g4_still_threshold
            value: 36 
        - number.set:
            id: g5_still_threshold
            value: 36 
        - number.set:
            id: g6_still_threshold
            value: 24 
        - number.set:
            id: g7_still_threshold
            value: 24 
        - number.set:
            id: g8_still_threshold
            value: 24 

  - platform: template
    name: "Still Presets 2"
    id: still_presets_2   
    icon: "mdi:signal-cellular-2"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_still_threshold
            value: 0 
        - number.set:
            id: g1_still_threshold
            value: 0 
        - number.set:
            id: g2_still_threshold
            value: 40 
        - number.set:
            id: g3_still_threshold
            value: 40 
        - number.set:
            id: g4_still_threshold
            value: 30 
        - number.set:
            id: g5_still_threshold
            value: 30 
        - number.set:
            id: g6_still_threshold
            value: 20 
        - number.set:
            id: g7_still_threshold
            value: 20 
        - number.set:
            id: g8_still_threshold
            value: 20 

  - platform: template
    name: "Still Presets 3"
    id: still_presets_3   
    icon: "mdi:signal-cellular-3"   
    entity_category: config
    on_press:
      then:
        - number.set:
            id: g0_still_threshold
            value: 0 
        - number.set:
            id: g1_still_threshold
            value: 0 
        - number.set:
            id: g2_still_threshold
            value: 36 
        - number.set:
            id: g3_still_threshold
            value: 36 
        - number.set:
            id: g4_still_threshold
            value: 27 
        - number.set:
            id: g5_still_threshold
            value: 27 
        - number.set:
            id: g6_still_threshold
            value: 18 
        - number.set:
            id: g7_still_threshold
            value: 18 
        - number.set:
            id: g8_still_threshold
            value: 18        
 
text_sensor:
  - platform: ld2410
    version:
      name: "firmware version"
      internal: true
  - platform: wifi_info
    ip_address:
      name: "IP"      
      icon: "mdi:ip-outline"
    ssid:
      name: "SSID"
      icon: "mdi:router-wireless"
    mac_address:
      name: "MAC"
      icon: "mdi:lan"
      
select:
  - platform: ld2410
    distance_resolution:
      name: "distance resolution"
    baud_rate:
      name: "baud rate"
      internal: true
    light_function:
      name: light function
    out_pin_level:
      name: out pin level

                                           
